CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "Courses" (
  "course_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "level" char(1) NOT NULL DEFAULT 'B',
  "Teacher" varchar NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "Categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "Course Videos" (
  "video_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "Users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "course_id" int
);

ALTER TABLE "Users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "Courses" ("course_id");

ALTER TABLE "Course Videos" ADD FOREIGN KEY ("course_id") REFERENCES "Courses" ("course_id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("category_id");
